export {
  composeKpFunctionSignatures,
  createKpScalarExpression,
  createKpScalarParameter,
  createKpTypedEquation,
  createKpTypedMatrix,
  createKpTypedVector,
  defineKpTypedFunction,
  evaluateKpTypedMatrix,
  isKpTypedVectorFunction,
  multiplyKpTypedMatrices,
  projectKpTypedMathToLatex,
  type KpFunctionType,
  type KpMathProvenance,
  type KpMathValueType,
  type KpMatrixType,
  type KpScalarExpression,
  type KpScalarParameter,
  type KpScalarType,
  type KpScalarValue,
  type KpTypedEquation,
  type KpTypedFunction,
  type KpTypedMathValue,
  type KpTypedMatrix,
  type KpTypedVector,
  type KpVectorType
} from "../typed-semantic-math.ts";
