import { strict as assert } from "node:assert";
import test from "node:test";

import {
  createSaddleDenominatorAnimationIntent,
  createSemanticObjectRef,
  createSemanticTransformationRef
} from "../src/semantic/animation.ts";
import {
  TRANSFORM_FIXTURE_CONTRACT_VERSION,
  exportKatexTransformFixture,
  importKatexTransformFixtureDocument,
  validateTransformFixtureDocument
} from "../src/authoring/transform-fixture-contract.ts";
import {
  expressionToLatex,
  power,
  variable
} from "../src/math/expression.ts";
import { findKatexTransformFixture } from "../src/rendering/katex-transform-fixtures.ts";
import { createKpDocument } from "../src/semantic/document.ts";
import type { KpDocument } from "../src/semantic/document.ts";
import {
  createAxis2DObject,
  createAxis3DObject,
  createDefaultGraphScene,
  createDefaultGraph3DScene,
  createGraph2DObject,
  createGraph3DObject,
  createParabolaCurve2D,
  createSaddleWeaveCurve3D,
  createSaddleSurface3D,
  createTimeSpiralCurve3D,
  graph3DSurfaceResolution,
  type Graph3DObject
} from "../src/semantic/graph.ts";
import {
  createLatexComparisonObject,
  createLatexFormObject
} from "../src/semantic/latex-form.ts";
import {
  deriveLinearMapFromMatrix
} from "../src/semantic/linear-map.ts";
import { createMatrixObject, identityMatrix } from "../src/semantic/matrix.ts";
import { createExpressionObject } from "../src/semantic/expression-object.ts";
import {
  createSourceFileObject,
  createSourceRangeProvenance,
  createSourceRangeSelector,
  resolveSourceRangeSelector,
  sourceFileLines
} from "../src/semantic/source-file.ts";
import {
  listSemanticComputationProtocols,
  semanticEvaluate,
  semanticMatrixForm,
  semanticToLatex
} from "../src/semantic/computation-protocols.ts";
import { validateKpDocument } from "../src/semantic/validation.ts";

test("createKpDocument creates a JSON-compatible semantic document", () => {
  const document = createKpDocument({
    id: "lesson-identity",
    title: "Identity matrix"
  });

  assert.deepEqual(document, {
    id: "lesson-identity",
    title: "Identity matrix",
    version: 1,
    objects: []
  });
  assert.equal(JSON.parse(JSON.stringify(document)).id, "lesson-identity");
});

test("transform fixture contract round-trips JSON-authored KaTeX fixtures", () => {
  const fixture = findKatexTransformFixture("radical.rewrite-power-as-root");
  const document = exportKatexTransformFixture(fixture);

  assert.equal(document.schemaVersion, TRANSFORM_FIXTURE_CONTRACT_VERSION);
  assert.equal(document.kind, "katex-transform-fixture");
  assert.deepEqual(JSON.parse(JSON.stringify(document)), document);

  const imported = importKatexTransformFixtureDocument(document);

  assert.equal(imported.ok, true);
  if (!imported.ok) {
    throw new Error("Expected exported transform fixture document to import.");
  }
  assert.deepEqual(imported.fixture, fixture);
});

test("transform fixture contract reports invalid LLM-authored fields", () => {
  const issues = validateTransformFixtureDocument({
    schemaVersion: TRANSFORM_FIXTURE_CONTRACT_VERSION,
    kind: "katex-transform-fixture",
    fixture: {
      id: "llm.bad-fixture",
      family: "unknown-family",
      intent: "rewritePowerAsRoot",
      source: {
        latex: "x",
        tokens: [
          {
            text: "x",
            signature: "semantic:x",
            role: "unknown-role",
            row: 0,
            column: 0
          }
        ]
      },
      target: {
        latex: "\\sqrt{x}",
        tokens: []
      },
      expectedStructuralTokens: {
        source: [],
        target: ["structural:sqrt-line"]
      },
      expectedRoleChanges: [
        {
          sourceRole: "base",
          targetRole: "radicand",
          sourceText: "x",
          targetText: "x"
        }
      ],
      summary: "Invalid fixture generated by an authoring model."
    }
  });

  assert.ok(issues.some((issue) => issue.path === "fixture.family"));
  assert.ok(issues.some((issue) => issue.path === "fixture.source.tokens[0].role"));
  assert.ok(issues.some((issue) => issue.path === "fixture.target.tokens"));

  const imported = importKatexTransformFixtureDocument({
    schemaVersion: 99,
    kind: "katex-transform-fixture",
    fixture: null
  });

  assert.equal(imported.ok, false);
});

test("createMatrixObject creates a semantic matrix object", () => {
  const matrix = createMatrixObject({
    id: "A",
    label: "A",
    rows: [
      [1, 2],
      [3, 4]
    ]
  });

  assert.deepEqual(matrix, {
    id: "A",
    type: "matrix",
    label: "A",
    rows: [
      [1, 2],
      [3, 4]
    ]
  });
});

test("createExpressionObject creates a semantic expression object", () => {
  const expression = createExpressionObject({
    id: "expr-x-squared",
    label: "x squared",
    expression: power(variable("x"), 2)
  });

  assert.deepEqual(expression, {
    id: "expr-x-squared",
    type: "expression",
    label: "x squared",
    expression: power(variable("x"), 2),
    variables: ["x"]
  });
  assert.deepEqual(
    validateKpDocument(
      createKpDocument({
        id: "expression-doc",
        title: "Expression",
        objects: [expression]
      })
    ),
    []
  );
});

test("createSourceFileObject creates a programming semantic object shell", () => {
  const source = createSourceFileObject({
    id: "source-file.add",
    label: "add.ts",
    language: "typescript",
    path: "src/add.ts",
    revisionId: "rev-1",
    sourceText: "export function add(a: number, b: number) {\n  return a + b;\n}\n"
  });

  assert.deepEqual(source, {
    id: "source-file.add",
    type: "source-file",
    label: "add.ts",
    language: "typescript",
    path: "src/add.ts",
    revisionId: "rev-1",
    sourceText: "export function add(a: number, b: number) {\n  return a + b;\n}\n",
    lineCount: 4
  });
  assert.deepEqual(sourceFileLines(source), [
    "export function add(a: number, b: number) {",
    "  return a + b;",
    "}",
    ""
  ]);
  assert.deepEqual(
    validateKpDocument(
      createKpDocument({
        id: "source-file-doc",
        title: "Source file",
        objects: [source]
      })
    ),
    []
  );
});

test("createSourceFileObject rejects empty source text", () => {
  assert.throws(
    () =>
      createSourceFileObject({
        id: "source-file.empty",
        label: "empty.ts",
        language: "typescript",
        sourceText: ""
      }),
    /source text must not be empty/
  );
});

test("source range selectors resolve one-based exclusive ranges", () => {
  const source = createSourceFileObject({
    id: "source-file.words",
    label: "words.txt",
    language: "text",
    sourceText: "alpha\nbeta\ngamma"
  });
  const selector = createSourceRangeSelector({
    id: "selector.words.alpha-to-beta",
    sourceFileId: source.id,
    start: { line: 1, column: 3 },
    end: { line: 2, column: 3 },
    summary: "Select the end of alpha and beginning of beta."
  });

  assert.deepEqual(selector, {
    id: "selector.words.alpha-to-beta",
    kind: "source-range",
    sourceFileId: "source-file.words",
    start: { line: 1, column: 3 },
    end: { line: 2, column: 3 },
    summary: "Select the end of alpha and beginning of beta."
  });
  assert.deepEqual(resolveSourceRangeSelector(source, selector), {
    selector,
    text: "pha\nbe",
    startOffset: 2,
    endOffset: 8
  });
});

test("source range provenance records stable revision and offset identity", () => {
  const source = createSourceFileObject({
    id: "source-file.words",
    label: "words.txt",
    language: "text",
    path: "fixtures/words.txt",
    revisionId: "rev-words-1",
    sourceText: "alpha\nbeta\ngamma"
  });
  const selector = createSourceRangeSelector({
    id: "selector.words.alpha-to-beta",
    sourceFileId: source.id,
    start: { line: 1, column: 3 },
    end: { line: 2, column: 3 },
    summary: "Select the end of alpha and beginning of beta."
  });

  assert.deepEqual(createSourceRangeProvenance(source, selector), {
    id: "provenance.source-file.words.selector.words.alpha-to-beta",
    kind: "source-range-provenance",
    sourceFileId: "source-file.words",
    selectorId: "selector.words.alpha-to-beta",
    language: "text",
    path: "fixtures/words.txt",
    revisionId: "rev-words-1",
    start: { line: 1, column: 3 },
    end: { line: 2, column: 3 },
    startOffset: 2,
    endOffset: 8,
    text: "pha\nbe",
    textHash: "fnv1a-270edc6f"
  });
});

test("source range selectors reject mismatched files and invalid positions", () => {
  const source = createSourceFileObject({
    id: "source-file.words",
    label: "words.txt",
    language: "text",
    sourceText: "alpha\nbeta"
  });

  assert.throws(
    () =>
      resolveSourceRangeSelector(
        source,
        createSourceRangeSelector({
          id: "selector.other",
          sourceFileId: "source-file.other",
          start: { line: 1, column: 1 },
          end: { line: 1, column: 2 }
        })
      ),
    /targets source-file.other/
  );
  assert.throws(
    () =>
      resolveSourceRangeSelector(
        source,
        createSourceRangeSelector({
          id: "selector.out-of-range",
          sourceFileId: source.id,
          start: { line: 2, column: 1 },
          end: { line: 2, column: 99 }
        })
      ),
    /line 2 column 99/
  );
});

test("semantic computation protocols expose matrix capabilities", () => {
  const matrix = createMatrixObject({
    id: "A",
    label: "A",
    rows: [
      [1, 2],
      [3, 4]
    ]
  });

  assert.deepEqual(listSemanticComputationProtocols(matrix), [
    "toLatex",
    "evaluate",
    "matrixForm"
  ]);
  assert.equal(
    semanticToLatex(matrix),
    String.raw`A = \begin{bmatrix}1 & 2 \\ 3 & 4\end{bmatrix}`
  );
  assert.equal(semanticMatrixForm(matrix), matrix);
  assert.deepEqual(semanticEvaluate(matrix), {
    kind: "matrix",
    rowCount: 2,
    columnCount: 2,
    isSquare: true,
    determinant: -2
  });
});

test("deriveLinearMapFromMatrix preserves matrix basis provenance", () => {
  const matrix = createMatrixObject({
    id: "A",
    label: "A",
    rows: [
      [1, 2, 3],
      [4, 5, 6]
    ]
  });
  const derivation = deriveLinearMapFromMatrix(matrix, {
    id: "linear-map.A",
    label: "T_A",
    domainBasisId: "basis.R3.standard",
    codomainBasisId: "basis.R2.standard"
  });

  assert.equal(derivation.object.type, "linear-map");
  assert.equal(derivation.object.sourceMatrixId, "A");
  assert.equal(derivation.object.domainDimension, 3);
  assert.equal(derivation.object.codomainDimension, 2);
  assert.deepEqual(derivation.object.rows, matrix.rows);
  assert.equal(derivation.object.domainBasisId, "basis.R3.standard");
  assert.equal(derivation.object.codomainBasisId, "basis.R2.standard");
  assert.equal(derivation.record.provenance.capabilityId, "matrix.linear-map");
  assert.equal(derivation.record.sourceObjectId, "A");
  assert.equal(derivation.record.targetObjectId, "linear-map.A");
  assert.deepEqual(listSemanticComputationProtocols(derivation.object), [
    "matrixForm"
  ]);
  assert.deepEqual(semanticMatrixForm(derivation.object)?.rows, matrix.rows);
  assert.equal(
    semanticToLatex(derivation.object),
    String.raw`T_A = \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6\end{bmatrix}`
  );
  assert.deepEqual(derivation.record.provenance.sourceSelectors, [
    "entry[0,0]",
    "entry[0,1]",
    "entry[0,2]",
    "entry[1,0]",
    "entry[1,1]",
    "entry[1,2]"
  ]);
  assert.deepEqual(
    validateKpDocument(
      createKpDocument({
        id: "linear-map-doc",
        title: "Linear map",
        objects: [matrix, derivation.object]
      })
    ),
    []
  );
});

test("semantic computation protocols expose authored LaTeX forms", () => {
  const formula = createLatexFormObject({
    id: "formula-fourier",
    label: "Fourier",
    latex: String.raw`\widehat{f}(\xi)=\int f(x)e^{-2\pi i x\xi}\,dx`,
    summary: "Fourier transform."
  });

  assert.deepEqual(listSemanticComputationProtocols(formula), ["toLatex"]);
  assert.equal(semanticToLatex(formula), formula.latex);
});

test("identityMatrix creates a square identity matrix object", () => {
  const matrix = identityMatrix({
    id: "identity-3x3",
    label: "I_3",
    size: 3
  });

  assert.deepEqual(matrix, {
    id: "identity-3x3",
    type: "matrix",
    label: "I_3",
    rows: [
      [1, 0, 0],
      [0, 1, 0],
      [0, 0, 1]
    ]
  });
});

test("createMatrixObject rejects ragged matrices", () => {
  assert.throws(
    () =>
      createMatrixObject({
        id: "bad",
        label: "B",
        rows: [[1], [2, 3]]
      }),
    /Matrix bad must be rectangular/
  );
});

test("identityMatrix rejects non-positive sizes", () => {
  assert.throws(
    () =>
      identityMatrix({
        id: "bad-identity",
        label: "I_0",
        size: 0
      }),
    /Identity matrix bad-identity size must be a positive integer/
  );
});

test("latex form objects and comparison cards preserve formula references", () => {
  const jacobian = createLatexFormObject({
    id: "formula-jacobian",
    label: "Jacobian",
    latex: String.raw`J_f(x) = \left[\frac{\partial f_i}{\partial x_j}\right]`,
    summary: "First-order local linear map for a vector-valued function."
  });
  const hessian = createLatexFormObject({
    id: "formula-hessian",
    label: "Hessian",
    latex: String.raw`H_f(x) = \left[\frac{\partial^2 f}{\partial x_i\partial x_j}\right]`,
    summary: "Second-order curvature matrix for a scalar-valued function."
  });
  const comparison = createLatexComparisonObject({
    id: "comparison-jacobian-hessian",
    label: "Jacobian / Hessian",
    formIds: [jacobian.id, hessian.id],
    summary: "Compare first- and second-derivative matrix forms."
  });

  assert.deepEqual(comparison.formIds, ["formula-jacobian", "formula-hessian"]);
  assert.deepEqual(
    validateKpDocument(
      createKpDocument({
        id: "comparison-doc",
        title: "Comparison",
        objects: [jacobian, hessian, comparison]
      })
    ),
    []
  );
  assert.deepEqual(
    validateKpDocument(
      createKpDocument({
        id: "bad-comparison-doc",
        title: "Bad comparison",
        objects: [jacobian, comparison]
      })
    ),
    [
      {
        path: "objects[1].formIds[1]",
        message:
          "LaTeX comparison comparison-jacobian-hessian references missing formula formula-hessian."
      }
    ]
  );
});

test("validateKpDocument reports matrix shape issues", () => {
  const document = {
    id: "bad-document",
    title: "Bad document",
    version: 1,
    objects: [
      {
        id: "bad",
        type: "matrix",
        label: "B",
        rows: [[1], [2, 3]]
      }
    ]
  } as unknown as KpDocument;

  assert.deepEqual(validateKpDocument(document), [
    {
      path: "objects[0].rows",
      message: "Matrix bad must be rectangular."
    }
  ]);
});

test("createGraph2DObject creates a semantic graph object", () => {
  const graph = createGraph2DObject({
    id: "parabola-graph",
    label: "Parabola graph",
    xAxisId: "parabola-x-axis",
    yAxisId: "parabola-y-axis",
    xDomain: [-3, 3],
    yDomain: [-1, 9],
    width: 520,
    height: 360
  });

  assert.deepEqual(graph, {
    id: "parabola-graph",
    type: "graph-2d",
    label: "Parabola graph",
    xAxisId: "parabola-x-axis",
    yAxisId: "parabola-y-axis",
    xDomain: [-3, 3],
    yDomain: [-1, 9],
    width: 520,
    height: 360
  });
});

test("createAxis2DObject creates semantic axis objects", () => {
  const axis = createAxis2DObject({
    id: "parabola-x-axis",
    graphId: "parabola-graph",
    label: "x",
    orientation: "x",
    domain: [-3, 3],
    tickStep: 1
  });

  assert.deepEqual(axis, {
    id: "parabola-x-axis",
    type: "axis-2d",
    graphId: "parabola-graph",
    label: "x",
    orientation: "x",
    domain: [-3, 3],
    tickStep: 1
  });
});

test("createParabolaCurve2D creates the x^2 = y curve object", () => {
  const curve = createParabolaCurve2D({
    id: "curve-y-equals-x-squared",
    graphId: "parabola-graph",
    xDomain: [-3, 3],
    sampleCount: 121
  });
  const { expression, ...curveMetadata } = curve;

  assert.deepEqual(curveMetadata, {
    id: "curve-y-equals-x-squared",
    type: "curve-2d",
    graphId: "parabola-graph",
    label: "x^2 = y",
    equation: "y = x^2",
    xDomain: [-3, 3],
    sampleCount: 121
  });
  assert.equal(expressionToLatex(expression), "x^{2}");
});

test("createDefaultGraphScene creates graph, axes, and curve objects", () => {
  const scene = createDefaultGraphScene();

  assert.deepEqual(
    scene.map((object) => object.type),
    ["graph-2d", "axis-2d", "axis-2d", "curve-2d"]
  );
  assert.equal(scene[0]?.id, "parabola-graph");
  assert.equal(scene[3]?.id, "curve-y-equals-x-squared");
});

test("createGraph3DObject creates a semantic graph object with a third axis", () => {
  const graph = createGraph3DObject({
    id: "saddle-orbit-graph",
    label: "Saddle surface and time spiral",
    xAxisId: "saddle-orbit-x-axis",
    yAxisId: "saddle-orbit-y-axis",
    zAxisId: "saddle-orbit-z-axis",
    xDomain: [-3, 3],
    yDomain: [-3, 3],
    zDomain: [-2.5, 2.5],
    width: 560,
    height: 420,
    occludedAxisLightness: 44,
    camera: {
      azimuthDegrees: 35,
      elevationDegrees: 30,
      scale: 58,
      origin: [280, 244]
    }
  });

  assert.deepEqual(graph, {
    id: "saddle-orbit-graph",
    type: "graph-3d",
    label: "Saddle surface and time spiral",
    xAxisId: "saddle-orbit-x-axis",
    yAxisId: "saddle-orbit-y-axis",
    zAxisId: "saddle-orbit-z-axis",
    xDomain: [-3, 3],
    yDomain: [-3, 3],
    zDomain: [-2.5, 2.5],
    width: 560,
    height: 420,
    surfaceMode: "mesh",
    surfaceQuality: "balanced",
    viewMode: "3d",
    occludedAxisLightness: 44,
    debug: {
      depthOverlay: false,
      surfaceMesh: false,
      shadowOverlay: false
    },
    shadow: {
      enabled: true,
      opacity: 0.16
    },
    light: {
      direction: { x: -0.35, y: -0.45, z: 0.82 },
      ambient: 0.45,
      diffuse: 0.4,
      depthHaze: 1,
      specular: 0.12,
      rim: 0.08
    },
    camera: {
      azimuthDegrees: 35,
      elevationDegrees: 30,
      scale: 58,
      origin: [280, 244]
    }
  });
});

test("graph3DSurfaceResolution maps quality levels to shared sample counts", () => {
  assert.deepEqual(graph3DSurfaceResolution("interactive"), {
    xSampleCount: 13,
    ySampleCount: 13,
    torusUSampleCount: 25,
    torusVSampleCount: 13
  });
  assert.deepEqual(graph3DSurfaceResolution("balanced"), {
    xSampleCount: 21,
    ySampleCount: 21,
    torusUSampleCount: 37,
    torusVSampleCount: 19
  });
  assert.deepEqual(graph3DSurfaceResolution("high"), {
    xSampleCount: 33,
    ySampleCount: 33,
    torusUSampleCount: 49,
    torusVSampleCount: 25
  });
});

test("createGraph3DObject preserves explicit graph shadow settings", () => {
  const graph = createGraph3DObject({
    id: "shadow-graph",
    label: "Shadow graph",
    xAxisId: "shadow-x-axis",
    yAxisId: "shadow-y-axis",
    zAxisId: "shadow-z-axis",
    xDomain: [-1, 1],
    yDomain: [-1, 1],
    zDomain: [-1, 1],
    width: 300,
    height: 220,
    shadow: {
      enabled: false,
      opacity: 2
    },
    camera: {
      azimuthDegrees: 35,
      elevationDegrees: 30,
      scale: 30,
      origin: [150, 110]
    }
  });

  assert.deepEqual(graph.shadow, {
    enabled: false,
    opacity: 1
  });
});

test("createGraph3DObject preserves explicit graph debug settings", () => {
  const graph = createGraph3DObject({
    id: "debug-graph",
    label: "Debug graph",
    xAxisId: "debug-x-axis",
    yAxisId: "debug-y-axis",
    zAxisId: "debug-z-axis",
    xDomain: [-1, 1],
    yDomain: [-1, 1],
    zDomain: [-1, 1],
    width: 300,
    height: 220,
    debug: {
      depthOverlay: true,
      surfaceMesh: true,
      shadowOverlay: true
    },
    camera: {
      azimuthDegrees: 35,
      elevationDegrees: 30,
      scale: 30,
      origin: [150, 110]
    }
  });

  assert.deepEqual(graph.debug, {
    depthOverlay: true,
    surfaceMesh: true,
    shadowOverlay: true
  });
});

test("createGraph3DObject preserves explicit graph light settings", () => {
  const graph = createGraph3DObject({
    id: "lit-graph",
    label: "Lit graph",
    xAxisId: "lit-x-axis",
    yAxisId: "lit-y-axis",
    zAxisId: "lit-z-axis",
    xDomain: [-1, 1],
    yDomain: [-1, 1],
    zDomain: [-1, 1],
    width: 300,
    height: 220,
    light: {
      direction: { x: 0, y: -0.25, z: 1 },
      ambient: 0.35,
      diffuse: 0.55,
      depthHaze: 0.5,
      specular: 2,
      rim: -1
    },
    camera: {
      azimuthDegrees: 35,
      elevationDegrees: 30,
      scale: 30,
      origin: [150, 110]
    }
  });

  assert.deepEqual(graph.light, {
    direction: { x: 0, y: -0.25, z: 1 },
    ambient: 0.35,
    diffuse: 0.55,
    depthHaze: 0.5,
    specular: 1,
    rim: 0
  });
});

test("createGraph3DObject preserves explicit graph surface mode", () => {
  const graph = createGraph3DObject({
    id: "mode-graph",
    label: "Mode graph",
    xAxisId: "mode-x-axis",
    yAxisId: "mode-y-axis",
    zAxisId: "mode-z-axis",
    xDomain: [-1, 1],
    yDomain: [-1, 1],
    zDomain: [-1, 1],
    width: 300,
    height: 220,
    surfaceMode: "donut",
    camera: {
      azimuthDegrees: 35,
      elevationDegrees: 30,
      scale: 30,
      origin: [150, 110]
    }
  });

  assert.equal(graph.surfaceMode, "donut");
});

test("createAxis3DObject creates semantic axis objects", () => {
  const axis = createAxis3DObject({
    id: "saddle-orbit-z-axis",
    graphId: "saddle-orbit-graph",
    label: "z",
    orientation: "z",
    domain: [-2.5, 2.5],
    tickStep: 1
  });

  assert.deepEqual(axis, {
    id: "saddle-orbit-z-axis",
    type: "axis-3d",
    graphId: "saddle-orbit-graph",
    label: "z",
    orientation: "z",
    domain: [-2.5, 2.5],
    tickStep: 1
  });
});

test("createSaddleSurface3D creates the z = (x^2 - y^2) / 4 surface", () => {
  const surface = createSaddleSurface3D({
    id: "saddle-surface",
    graphId: "saddle-orbit-graph",
    xDomain: [-3, 3],
    yDomain: [-3, 3],
    xSampleCount: 13,
    ySampleCount: 13
  });
  const { expression, ...surfaceMetadata } = surface;

  assert.deepEqual(surfaceMetadata, {
    id: "saddle-surface",
    type: "surface-3d",
    graphId: "saddle-orbit-graph",
    label: "z = (x^2 - y^2) / 4",
    equation: "z = (x^2 - y^2) / 4",
    parameterization: {
      kind: "saddle",
      denominator: 4
    },
    xDomain: [-3, 3],
    yDomain: [-3, 3],
    xSampleCount: 13,
    ySampleCount: 13
  });
  assert.equal(expressionToLatex(expression), "\\frac{x^{2} - y^{2}}{4}");
});

test("createSaddleSurface3D creates a parameterized saddle surface", () => {
  const surface = createSaddleSurface3D({
    id: "flat-saddle-surface",
    graphId: "saddle-orbit-graph",
    denominator: 8,
    xDomain: [-3, 3],
    yDomain: [-3, 3],
    xSampleCount: 13,
    ySampleCount: 13
  });

  assert.equal(surface.label, "z = (x^2 - y^2) / 8");
  assert.equal(surface.equation, "z = (x^2 - y^2) / 8");
  assert.deepEqual(surface.parameterization, {
    kind: "saddle",
    denominator: 8
  });
  assert.equal(expressionToLatex(surface.expression), "\\frac{x^{2} - y^{2}}{8}");
});

test("createTimeSpiralCurve3D creates a time-visible spiral curve", () => {
  const curve = createTimeSpiralCurve3D({
    id: "time-spiral-curve",
    graphId: "saddle-orbit-graph",
    tDomain: [0, Math.PI * 4],
    sampleCount: 145
  });
  const { expressions, ...curveMetadata } = curve;

  assert.deepEqual(curveMetadata, {
    id: "time-spiral-curve",
    type: "curve-3d",
    graphId: "saddle-orbit-graph",
    label: "time spiral",
    equation: {
      x: "2.2 cos(t)",
      y: "1.3 sin(t)",
      z: "0.18 (t - 2 pi)"
    },
    tDomain: [0, Math.PI * 4],
    sampleCount: 145
  });
  assert.equal(expressionToLatex(expressions.x), "2.2 \\cos\\left(t\\right)");
  assert.equal(expressionToLatex(expressions.y), "1.3 \\sin\\left(t\\right)");
  assert.equal(
    expressionToLatex(expressions.z),
    "0.18 \\left(t - 6.283185\\right)"
  );
});

test("createSaddleWeaveCurve3D creates a saddle depth test curve", () => {
  const curve = createSaddleWeaveCurve3D({
    id: "saddle-weave-curve",
    graphId: "saddle-orbit-graph",
    tDomain: [-3, 3],
    sampleCount: 121
  });
  const { expressions, ...curveMetadata } = curve;

  assert.deepEqual(curveMetadata, {
    id: "saddle-weave-curve",
    type: "curve-3d",
    graphId: "saddle-orbit-graph",
    label: "saddle weave",
    equation: {
      x: "t",
      y: "0",
      z: "t^2 / 4 + 0.25 sin(2t)"
    },
    tDomain: [-3, 3],
    sampleCount: 121
  });
  assert.equal(expressionToLatex(expressions.x), "t");
  assert.equal(expressionToLatex(expressions.y), "0");
  assert.equal(
    expressionToLatex(expressions.z),
    "\\frac{t^{2}}{4} + 0.25 \\sin\\left(2 t\\right)"
  );
});

test("createDefaultGraph3DScene creates graph, axes, and surface objects", () => {
  const scene = createDefaultGraph3DScene();

  assert.deepEqual(
    scene.map((object) => object.type),
    ["graph-3d", "axis-3d", "axis-3d", "axis-3d", "surface-3d"]
  );
  assert.equal(scene[0]?.id, "saddle-orbit-graph");
  assert.equal(scene[4]?.id, "saddle-surface");
  assert.equal(
    scene[0]?.type === "graph-3d"
      ? scene[0].occludedAxisLightness
      : undefined,
    44
  );
  assert.deepEqual(
    scene[0]?.type === "graph-3d" ? scene[0].debug : undefined,
    {
      depthOverlay: false,
      surfaceMesh: false,
      shadowOverlay: false
    }
  );
  assert.equal(
    scene[0]?.type === "graph-3d" ? scene[0].surfaceMode : undefined,
    "mesh"
  );
  assert.equal(
    scene[0]?.type === "graph-3d" ? scene[0].surfaceQuality : undefined,
    "balanced"
  );
});

test("validateKpDocument reports invalid graph surface quality", () => {
  const scene = createDefaultGraph3DScene();
  const document = createKpDocument({
    id: "bad-graph-quality-document",
    title: "Bad graph quality",
    objects: scene.map((object) =>
      object.type === "graph-3d"
        ? ({
            ...object,
            surfaceQuality: "ultra"
          } as unknown as Graph3DObject)
        : object
    )
  });

  assert.deepEqual(validateKpDocument(document), [
    {
      path: "objects[0].surfaceQuality",
      message:
        "Graph saddle-orbit-graph surfaceQuality must be interactive, balanced, or high."
    }
  ]);
});

test("createSaddleDenominatorAnimationIntent creates a semantic animation intent", () => {
  const intent = createSaddleDenominatorAnimationIntent({
    id: "flatten-saddle",
    label: "flatten saddle",
    targetId: "saddle-surface",
    fromDenominator: 4,
    toDenominator: 8,
    durationMs: 900
  });

  assert.deepEqual(intent, {
    id: "flatten-saddle",
    type: "animation-intent",
    label: "flatten saddle",
    targetId: "saddle-surface",
    targetType: "surface-3d",
    property: "saddle.denominator",
    from: 4,
    to: 8,
    durationMs: 900,
    easing: "ease-in-out"
  });
});

test("semantic animation refs preserve object and transformation provenance", () => {
  const objectRef = createSemanticObjectRef({
    objectId: "matrix.A",
    objectType: "matrix",
    selectorId: "entry.0.0",
    revisionId: "rev-1"
  });
  const sourceObjectIds = ["matrix.A"];
  const targetObjectIds = ["matrix.B"];
  const preserves = ["identity", "structure"] as const;
  const transformationRef = createSemanticTransformationRef({
    id: "matrix.scale.row",
    kind: "scaleRow",
    sourceObjectIds,
    targetObjectIds,
    preserves,
    summary: "Scale a row while preserving matrix structure."
  });

  sourceObjectIds.push("mutated");
  targetObjectIds.push("mutated");

  assert.deepEqual(objectRef, {
    objectId: "matrix.A",
    objectType: "matrix",
    selectorId: "entry.0.0",
    revisionId: "rev-1"
  });
  assert.deepEqual(transformationRef, {
    id: "matrix.scale.row",
    kind: "scaleRow",
    sourceObjectIds: ["matrix.A"],
    targetObjectIds: ["matrix.B"],
    preserves: ["identity", "structure"],
    summary: "Scale a row while preserving matrix structure."
  });
});

test("validateKpDocument reports graph reference issues", () => {
  const document = createKpDocument({
    id: "bad-graph-document",
    title: "Bad graph",
    objects: [
      createGraph2DObject({
        id: "bad-graph",
        label: "Bad graph",
        xAxisId: "missing-x-axis",
        yAxisId: "missing-y-axis",
        xDomain: [3, -3],
        yDomain: [-1, 9],
        width: 520,
        height: 360
      }),
      createParabolaCurve2D({
        id: "orphan-curve",
        graphId: "missing-graph",
        xDomain: [-3, 3],
        sampleCount: 121
      })
    ]
  });

  assert.deepEqual(validateKpDocument(document), [
    {
      path: "objects[0].xDomain",
      message: "Graph bad-graph xDomain must increase from min to max."
    },
    {
      path: "objects[0].xAxisId",
      message: "Graph bad-graph references missing x-axis missing-x-axis."
    },
    {
      path: "objects[0].yAxisId",
      message: "Graph bad-graph references missing y-axis missing-y-axis."
    },
    {
      path: "objects[1].graphId",
      message: "Curve orphan-curve references missing graph missing-graph."
    }
  ]);
});

test("validateKpDocument reports animation intent issues", () => {
  const document = createKpDocument({
    id: "bad-animation-document",
    title: "Bad animation",
    objects: [
      createSaddleDenominatorAnimationIntent({
        id: "bad-animation",
        label: "bad animation",
        targetId: "missing-surface",
        fromDenominator: 4,
        toDenominator: 8,
        durationMs: 0
      })
    ]
  });

  assert.deepEqual(validateKpDocument(document), [
    {
      path: "objects[0].targetId",
      message: "Animation bad-animation references missing surface missing-surface."
    },
    {
      path: "objects[0].durationMs",
      message: "Animation bad-animation durationMs must be positive."
    }
  ]);
});

test("validateKpDocument reports 3D graph reference issues", () => {
  const document = createKpDocument({
    id: "bad-graph-3d-document",
    title: "Bad 3D graph",
    objects: [
      createGraph3DObject({
        id: "bad-graph-3d",
        label: "Bad 3D graph",
        xAxisId: "missing-x-axis",
        yAxisId: "missing-y-axis",
        zAxisId: "missing-z-axis",
        xDomain: [-3, 3],
        yDomain: [3, -3],
        zDomain: [-2.5, 2.5],
        width: 560,
        height: 420,
        camera: {
          azimuthDegrees: 35,
          elevationDegrees: 30,
          scale: 58,
          origin: [280, 244]
        }
      }),
      createTimeSpiralCurve3D({
        id: "orphan-curve-3d",
        graphId: "missing-graph",
        tDomain: [0, Math.PI * 2],
        sampleCount: 145
      }),
      createSaddleSurface3D({
        id: "bad-surface-3d",
        graphId: "missing-graph",
        xDomain: [-3, 3],
        yDomain: [-3, 3],
        xSampleCount: 1,
        ySampleCount: 13
      })
    ]
  });

  assert.deepEqual(validateKpDocument(document), [
    {
      path: "objects[0].yDomain",
      message: "Graph bad-graph-3d yDomain must increase from min to max."
    },
    {
      path: "objects[0].xAxisId",
      message: "Graph bad-graph-3d references missing x-axis missing-x-axis."
    },
    {
      path: "objects[0].yAxisId",
      message: "Graph bad-graph-3d references missing y-axis missing-y-axis."
    },
    {
      path: "objects[0].zAxisId",
      message: "Graph bad-graph-3d references missing z-axis missing-z-axis."
    },
    {
      path: "objects[1].graphId",
      message: "Curve orphan-curve-3d references missing graph missing-graph."
    },
    {
      path: "objects[2].graphId",
      message: "Surface bad-surface-3d references missing graph missing-graph."
    },
    {
      path: "objects[2].xSampleCount",
      message: "Surface bad-surface-3d xSampleCount must be an integer of at least 2."
    }
  ]);
});
