import type {
  KpEquationDispatchDeclaration,
  KpEquationDispatchKind
} from "./equation-extension-dispatch-manifest.ts";

const tableNames = Object.freeze({
  operation: "kpEquationOperationLoaders",
  recipe: "kpEquationRecipeLoaders",
  motif: "kpEquationMotifLoaders",
  "renderer-capability": "kpEquationRendererCapabilityLoaders",
  "lazy-pack": "kpEquationLazyPackLoaders"
} as const satisfies Readonly<Record<KpEquationDispatchKind, string>>);

const functionNames = Object.freeze({
  operation: "loadKpEquationOperation",
  recipe: "loadKpEquationRecipe",
  motif: "loadKpEquationMotif",
  "renderer-capability": "loadKpEquationRendererCapability",
  "lazy-pack": "loadKpEquationExtensionPack"
} as const satisfies Readonly<Record<KpEquationDispatchKind, string>>);

export function renderKpEquationExtensionDispatchSource(
  declarations: readonly KpEquationDispatchDeclaration[]
): string {
  validateDeclarations(declarations);
  const kinds = Object.keys(tableNames) as KpEquationDispatchKind[];
  const tables = kinds.map((kind) => renderTable(
    tableNames[kind],
    declarations.filter((declaration) => declaration.kind === kind)
  )).join("\n\n");
  const functions = kinds.map((kind) => {
    const label = kind.replaceAll("-", " ");
    return `export function ${functionNames[kind]}(id: string): Promise<unknown> {\n` +
      `  return loadGenerated(${tableNames[kind]}, id, ${JSON.stringify(label)});\n` +
      `}`;
  }).join("\n\n");
  return `/* This file is generated by npm run generate:equation-extension-dispatch. */\n` +
    `type KpGeneratedLoader = () => Promise<unknown>;\n\n` +
    `${tables}\n\n` +
    `export const kpGeneratedEquationDispatchIds = Object.freeze({\n` +
    kinds.map((kind) => {
      const ids = declarations
        .filter((declaration) => declaration.kind === kind)
        .map(({ id }) => JSON.stringify(id));
      return `  ${JSON.stringify(kind)}: Object.freeze([${ids.join(", ")}])`;
    }).join(",\n") +
    `\n});\n\n` +
    `${functions}\n\n` +
    `function loadGenerated(\n` +
    `  loaders: Readonly<Record<string, KpGeneratedLoader>>,\n` +
    `  id: string,\n` +
    `  label: string\n` +
    `): Promise<unknown> {\n` +
    `  const loader = loaders[id];\n` +
    `  if (loader === undefined) {\n` +
    "    return Promise.reject(new Error(`Unknown equation ${label} ${id}.`));\n" +
    `  }\n` +
    `  return loader();\n` +
    `}\n`;
}

function renderTable(
  tableName: string,
  declarations: readonly KpEquationDispatchDeclaration[]
): string {
  const entries = declarations.map((declaration) =>
    `  ${JSON.stringify(declaration.id)}: () => import(${JSON.stringify(declaration.modulePath)})` +
    `.then((module) => module.${declaration.exportName})`
  );
  return `const ${tableName}: Readonly<Record<string, KpGeneratedLoader>> = ` +
    `Object.freeze({\n${entries.join(",\n")}\n});`;
}

function validateDeclarations(
  declarations: readonly KpEquationDispatchDeclaration[]
): void {
  const keys = new Set<string>();
  for (const declaration of declarations) {
    for (const [label, value] of [
      ["id", declaration.id],
      ["module path", declaration.modulePath],
      ["export name", declaration.exportName]
    ] as const) {
      if (value.trim() === "") {
        throw new Error(`Equation dispatch ${label} must not be empty.`);
      }
    }
    if (!/^\.\.\/(?:[a-z0-9-]+\/)+[a-z0-9-]+\.ts$/u.test(declaration.modulePath)) {
      throw new Error(`Equation dispatch module path must be a literal repository module: ${declaration.modulePath}.`);
    }
    if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(declaration.exportName)) {
      throw new Error(`Equation dispatch export is not an identifier: ${declaration.exportName}.`);
    }
    const key = `${declaration.kind}\u0000${declaration.id}`;
    if (keys.has(key)) {
      throw new Error(`Duplicate equation ${declaration.kind} dispatch id ${declaration.id}.`);
    }
    keys.add(key);
  }
}
