import { readFile, writeFile } from "node:fs/promises";
import { createKpAnimationAssets } from "../src/animation/catalog.ts";
import { compileKpAnimationConformanceManifestSet } from
  "../src/architecture/animation-conformance-manifest.ts";
import { compileKpAnimationGovernanceInventory } from
  "../src/architecture/animation-governance-inventory.ts";
import { createKpAnimationCatalogueProjection } from
  "../src/editor/animation-catalogue-projection.ts";
import { createKpEditorAnimationLibrary } from
  "../src/editor/animation-library.ts";
import { kpEditorSelectedSurfaceCapabilityDeclarationSet } from
  "../src/editor/selected-surface-capability-declarations.ts";

const target = new URL(
  "../src/generated/animation-conformance-registrations.generated.ts",
  import.meta.url
);
const assets = createKpAnimationAssets();
const descriptors = createKpEditorAnimationLibrary();
const inventory = compileKpAnimationGovernanceInventory({
  assets,
  catalogue: createKpAnimationCatalogueProjection({ descriptors }),
  descriptors,
  capabilityDeclarations: kpEditorSelectedSurfaceCapabilityDeclarationSet
});
const manifests = compileKpAnimationConformanceManifestSet({
  assets,
  inventory
});
const packByAssetId = new Map(inventory.entries.map(({ assetId, packId }) =>
  [assetId, packId]
));
const declarations = manifests.manifests.map((manifest) => ({
  kind: "manifest-ref" as const,
  assetId: manifest.assetId,
  packId: packByAssetId.get(manifest.assetId),
  manifestId: `manifest.${manifest.assetId}`,
  policyEpochId: manifest.policy.epochId,
  disposition: manifest.disposition.status
}));
const output = `// Generated by npm run generate:animation-conformance-registrations.\n` +
  `import type { KpAnimationConformanceRegistrationDeclaration } from\n` +
  `  "../animation/animation-conformance-registration.ts";\n\n` +
  `export const kpAnimationConformanceRegistrationDeclarations = ` +
  `${JSON.stringify(declarations, null, 2)} as const satisfies ` +
  `readonly KpAnimationConformanceRegistrationDeclaration[];\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== output) {
    throw new Error(
      "Animation conformance registrations are stale. Run " +
      "npm run generate:animation-conformance-registrations."
    );
  }
  console.log("animation conformance registrations are current");
} else {
  await writeFile(target, output, "utf8");
  console.log("generated animation conformance registrations");
}
