import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import {
  kpHessianConstructDescriptor,
  kpJacobianConstructDescriptor,
  type KpSemanticConstructDescriptor
} from "../src/math/authoring/construct-descriptor.ts";

const generatedPath = resolve(
  import.meta.dirname,
  "../src/math/authoring/generated/construct-plumbing.generated.ts"
);

export function renderKpTypedMathConstructPlumbing(
  descriptors: readonly KpSemanticConstructDescriptor[] = [
    kpJacobianConstructDescriptor,
    kpHessianConstructDescriptor
  ]
): string {
  const constructs = [...descriptors]
    .sort((left, right) => left.construct.localeCompare(right.construct))
    .map((descriptor) => ({
      construct: descriptor.construct,
      descriptorId: descriptor.id,
      macro: descriptor.macro,
      childInventory: descriptor.children.map((child) => ({
        role: child.role,
        path: child.path,
        cardinality: child.cardinality
      })),
      optics: descriptor.children.map((child) => ({
        id: `${descriptor.id}.optic.${child.role}`,
        role: child.role,
        path: child.path
      })),
      correspondence: {
        id: `${descriptor.id}.correspondence.compact-to-entries`,
        relation: "fan-out",
        sourceRole: "compact",
        targetRole: "entry"
      },
      serializationFields: [
        "descriptorId",
        "macroId",
        "sourceFunctionId",
        "projectionForm",
        "authorityIds",
        "childIds"
      ],
      autocomplete: {
        label: capitalize(descriptor.construct),
        projectionForms: descriptor.projections.map(({ form }) => form),
        capabilityRequirements: descriptor.capabilityRequirements
      },
      conformanceCases: descriptor.projections.map((projection) => ({
        id: `${descriptor.id}.conformance.${projection.form}`,
        form: projection.form,
        requiredCapabilities: projection.requires
      }))
    }));
  const value = {
    schemaVersion: "kp.typed-math.construct-plumbing.v1",
    constructs
  };
  return "// Generated by scripts/generate-typed-math-construct-plumbing.ts.\n" +
    "// Descriptor metadata only; mathematical rules remain in authored code.\n" +
    `export const kpGeneratedConstructPlumbing = ${JSON.stringify(
      value,
      null,
      2
    )} as const;\n`;
}

function capitalize(value: string): string {
  return `${value.slice(0, 1).toUpperCase()}${value.slice(1)}`;
}

const invokedPath = process.argv[1];
if (
  invokedPath !== undefined &&
  pathToFileURL(resolve(invokedPath)).href === import.meta.url
) {
  mkdirSync(dirname(generatedPath), { recursive: true });
  writeFileSync(generatedPath, renderKpTypedMathConstructPlumbing());
}
