import { existsSync, mkdirSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { pathToFileURL } from "node:url";

import {
  canonicalJson,
  defineConceptCatalog,
  draftConceptManifestSchema,
  publishConceptDraft,
  type KpConceptDraftSource,
  type KpGeneratedConceptCatalogEntry,
  type KpPublishedConceptArtifact
} from "../src/authoring/public-api.ts";

const projectRoot = process.cwd();
const contentRoot = join(projectRoot, "content");
const generatedRoot = join(contentRoot, "generated");
const artifactRoot = join(generatedRoot, "artifacts");
const checkOnly = process.argv.includes("--check");

const outputs = await generateConceptCatalogOutputs(await discoverConcepts());
const errors = checkOnly ? checkOutputs(outputs) : writeOutputs(outputs);
if (errors.length > 0) {
  errors.forEach((error) => console.error(error));
  process.exitCode = 1;
} else {
  console.log(`${checkOnly ? "fresh" : "generated"} concept catalog (${outputs.size} files)`);
}

export async function generateConceptCatalogOutputs(
  concepts: readonly KpConceptDraftSource[]
): Promise<ReadonlyMap<string, string>> {
  const published = await Promise.all(concepts.map((concept) => publishConceptDraft(concept)));
  const records = published.map((artifact) => catalogRecord(artifact));
  defineConceptCatalog(records.map((record) => record.entry));
  const ordered = records.sort((left, right) =>
    left.entry.conceptId.localeCompare(right.entry.conceptId) ||
    left.entry.version.localeCompare(right.entry.version)
  );
  const outputs = new Map<string, string>();
  for (const record of ordered) {
    outputs.set(join(artifactRoot, record.fileName), renderArtifactModule(record.artifact));
  }
  outputs.set(join(generatedRoot, "catalog.ts"), renderCatalog(ordered));
  return outputs;
}

async function discoverConcepts(): Promise<readonly KpConceptDraftSource[]> {
  const files = [...collectConceptSources(contentRoot)].sort();
  return Promise.all(files.map(async (path) => {
    const module = await import(pathToFileURL(path).href) as { readonly default?: unknown };
    return draftConceptManifestSchema.parse(module.default);
  }));
}

function collectConceptSources(root: string): readonly string[] {
  return readdirSync(root, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name === "generated") return [];
    const path = join(root, entry.name);
    if (entry.isDirectory()) return collectConceptSources(path);
    return entry.isFile() && entry.name === "concept.ts" ? [path] : [];
  });
}

function catalogRecord(artifact: KpPublishedConceptArtifact): {
  readonly artifact: KpPublishedConceptArtifact;
  readonly fileName: string;
  readonly entry: KpGeneratedConceptCatalogEntry;
} {
  const manifest = artifact.manifest;
  const fileName = `${manifest.conceptId}--${manifest.version}.ts`;
  return {
    artifact,
    fileName,
    entry: {
      conceptId: manifest.conceptId,
      version: manifest.version,
      canonicalPath: manifest.route.canonicalPath,
      legacyAliases: manifest.route.legacyAliases,
      title: manifest.review.title,
      summary: manifest.review.summary,
      searchableText: manifest.review.searchableText,
      checkpointIds: manifest.checkpoints.map((checkpoint) => checkpoint.id),
      preload: artifact.assets.map((asset) => asset.path),
      load: async () => artifact
    }
  };
}

function renderArtifactModule(artifact: KpPublishedConceptArtifact): string {
  return `// Generated by scripts/generate-concept-catalog.ts. Do not edit.\n` +
    `const artifact = ${JSON.stringify(artifact, null, 2)} as const;\n\nexport default artifact;\n`;
}

function renderCatalog(records: readonly ReturnType<typeof catalogRecord>[]): string {
  const entries = records.map(({ entry, fileName }) => `  {
    conceptId: ${JSON.stringify(entry.conceptId)},
    version: ${JSON.stringify(entry.version)},
    canonicalPath: ${JSON.stringify(entry.canonicalPath)},
    legacyAliases: ${canonicalJson(entry.legacyAliases)},
    title: ${JSON.stringify(entry.title)},
    summary: ${JSON.stringify(entry.summary)},
    searchableText: ${JSON.stringify(entry.searchableText)},
    checkpointIds: ${canonicalJson(entry.checkpointIds)},
    preload: ${canonicalJson(entry.preload)},
    load: async () => publishedConceptArtifactSchema.parse(
      (await import(${JSON.stringify(`./artifacts/${fileName}`)})).default
    )
  }`).join(",\n");
  return `// Generated by scripts/generate-concept-catalog.ts. Do not edit.\n` +
    `import {\n  defineConceptCatalog,\n  publishedConceptArtifactSchema,\n  type KpGeneratedConceptCatalogEntry\n} from "../../src/authoring/public-api.ts";\n\n` +
    `export type GeneratedConceptCatalogEntry = KpGeneratedConceptCatalogEntry;\n\n` +
    `export const generatedConceptCatalog = defineConceptCatalog([\n${entries}\n]);\n`;
}

function checkOutputs(outputs: ReadonlyMap<string, string>): string[] {
  const errors: string[] = [];
  for (const [path, expected] of outputs) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== expected) {
      errors.push(`stale generated concept output: ${relative(projectRoot, path)}`);
    }
  }
  for (const path of existingArtifactFiles()) {
    if (!outputs.has(path)) errors.push(`unexpected generated concept artifact: ${relative(projectRoot, path)}`);
  }
  return errors;
}

function writeOutputs(outputs: ReadonlyMap<string, string>): string[] {
  mkdirSync(artifactRoot, { recursive: true });
  for (const path of existingArtifactFiles()) {
    if (!outputs.has(path)) unlinkSync(path);
  }
  for (const [path, source] of outputs) writeFileSync(path, source);
  return [];
}

function existingArtifactFiles(): readonly string[] {
  if (!existsSync(artifactRoot)) return [];
  return readdirSync(artifactRoot)
    .filter((name) => name.endsWith(".ts"))
    .map((name) => join(artifactRoot, basename(name)));
}
