import { renderLatexToHtml } from "../../rendering/katex-adapter.ts";

// These are selections of the primary's existing visual evidence, not new
// animation capabilities. Coordinate arithmetic is deliberately static math.
export type GradientEvidence = "hillside" | "ramp" | "gradient-ramp" | "level-ramp" | "projection" | "uphill" | "contour" | "follow" | "tangent";
const math = (latex: string) => renderLatexToHtml(latex, { displayMode: false, output: "htmlAndMathml" });
export const gradientComparisonReading = Object.freeze({
  prepare: Object.freeze({
    lead: "Keep the arrow’s tip on the circle.",
    body: "Every radius has the same length. The across part is its northeast projection; the along part adds no rise. Can the across part reach the whole radius?"
  }),
  conclude: Object.freeze({
    lead: "The across part is now the whole arrow.",
    body: "No same-length arrow can project farther. Turning away shortens this part and gives less rise. Northeast wins—and that is the gradient’s direction."
  })
});

export const gradientContourBeats = Object.freeze([
  { slug: "height", evidence: "hillside", title: "What height cannot tell you", html: "<p>You’re standing on a hillside, trying to gain height as quickly as possible. Your current height cannot tell you <strong>which way to move</strong>. On a one-way path, a slope tells you how much height a small forward move gains. On a hillside there are many directions. One slope is no longer enough.</p>" },
  { slug: "east", evidence: "hillside", title: "Measure one direction", html: `<p>Start with a simple measurement: move a tiny distance east while keeping your north–south position fixed. Here the eastward slope is ${math("f_x=2")}: a move of 0.01 predicts about 0.02 more height. This is a <strong>partial derivative</strong>—a slope measured by changing one coordinate while holding the other fixed.</p>` },
  { slug: "north", evidence: "hillside", title: "Then measure the other", html: `<p>Now hold your east–west position fixed and measure northward change. Here ${math("f_y=2")} too. A tiny northward move of 0.01 also predicts about 0.02 more height. These are <strong>local slopes at the marked point</strong>, not promises about the whole hillside. Both horizontal coordinates use the same distance units.</p>` },
  { slug: "ramp", evidence: "ramp", title: "Why the contributions add", html: "<p>Very close to this smooth hillside, the surface is almost a <strong>flat ramp</strong>. On that ramp, the eastward and northward contributions add. The magnified sketch shows local rise above the starting height. It is a local approximation, not a claim that the curved hillside stays flat over a large move.</p>" },
  { slug: "linear-change", evidence: "ramp", title: "Predict a diagonal move", html: `<p>Write the eastward and northward parts of a tiny move as ${math("\\Delta x")} and ${math("\\Delta y")}. Then ${math("\\Delta f\\approx2\\Delta x+2\\Delta y")}. Moving 0.01 east and 0.01 north predicts a gain of 0.04. But that diagonal move is longer than a 0.01 east-only move: we have predicted a change, <strong>not yet compared slopes fairly</strong>.</p>` },
  { slug: "gradient", evidence: "gradient-ramp", title: "The gradient packages those slopes", html: `<p>Collect the two local slopes into one pair: ${math("\\nabla f=(2,2)")}. This is the <strong>gradient</strong>. As an arrow, the pair points two units east and two north—northeast. It packages the information that predicts changes in any small direction. Why should this particular direction give the fastest increase?</p>` },
  { slug: "fair-comparison", evidence: "gradient-ramp", title: "Make the comparison fair", html: "<p>Allow the <strong>same small horizontal distance</strong> in every direction. We are comparing height gained per distance, not giving one direction a longer step or comparing how tiring it is to walk. The diagram uses unit-length directions to compare these local rates; it does not predict distant endpoints on the curved hill.</p>" },
  { slug: "level", evidence: "level-ramp", title: "Find a direction that adds nothing", html: "<p>On our local ramp, a southeast move gains height from its eastward part but loses the same amount from its southward part. They cancel. Northwest does the reverse, also with zero rise. The dotted level lines run in those directions. Northeast instead combines two positive contributions.</p>" },
  { slug: "projection", evidence: "projection", title: "What a projection means", html: "<p>Look down on equal-length arrows: their tips lie on a circle. Split a move into a northeast part and a part along a level line. The level part adds no rise. The northeast part is its <strong>projection</strong>: drop a perpendicular from the tip onto the northeast line. This is signed forward reach; backward reach is negative.</p>" },
  { slug: "components", evidence: "projection", title: "Can the projection be longer?", html: `<p>${gradientComparisonReading.prepare.lead} ${gradientComparisonReading.prepare.body}</p>` },
  { slug: "across", evidence: "uphill", title: "Why the gradient wins", html: `<p>${gradientComparisonReading.conclude.lead} ${gradientComparisonReading.conclude.body}</p>` },
  { slug: "dot-product", evidence: "uphill", title: "The same rule beyond this example", html: `<p>For any smooth field, the local change rule is ${math("\\Delta f\\approx f_x\\Delta x+f_y\\Delta y")}. Writing ${math("\\nabla f\\cdot\\Delta\\mathbf r")} means the same thing. The dot is a <strong>dot product</strong>: multiply each coordinate slope by its coordinate movement, then add. It is not an extra measurement.</p>` },
  { slug: "general-projection", evidence: "uphill", title: "Connect the formula to the picture", html: "<p>The dot product also equals the <strong>gradient’s length times your move’s signed projection onto its direction</strong>. So the same comparison works even when the slopes differ: fixed-length moves have greatest projection when aligned with the gradient. Perpendicular moves have zero local rise; opposite moves have negative rise. Northeast was our example, not a universal compass direction.</p>" },
  { slug: "magnitude", evidence: "uphill", title: "Direction and rate, not a commanded step", html: `<p>The gradient’s direction tells you which way increases the quantity fastest. Its length gives the greatest local increase per unit horizontal distance: here ${math("\\lVert\\nabla f\\rVert=\\sqrt{2^2+2^2}=\\sqrt8\\approx2.83")}. You do not need to travel the length of that arrow. The drawn unit direction compares rates; the gradient encodes both <strong>direction and rate</strong>.</p>` },
  { slug: "contour", evidence: "contour", title: "Now read the contour map", html: "<p>A <strong>contour</strong> joins positions with the same height. The highlighted curve is at height 1.50. This map is another way to read what we already know: some directions change position without initially changing height. Follow the highlighted curve next to see what staying at one height requires.</p>" },
  { slug: "follow", evidence: "follow", title: "Travel without climbing", html: "<p>As the point travels around the contour, its position changes but its height stays at 1.50. The curve bends to keep it level. At the starting point, the curve’s immediate direction is called its <strong>tangent</strong>. What should its relationship to the gradient be?</p>" },
  { slug: "tangent", evidence: "tangent", title: "Why the right angle follows", html: "<p>Along the contour tangent, the instantaneous rise is zero. We already found that zero-rise directions are <strong>perpendicular to the gradient</strong>. That is why the gradient crosses the contour at a right angle, toward increasing heights. The contour confirms the gradient’s meaning; it was not needed to define it.</p>" },
  { slug: "local", evidence: "tangent", title: "What this does—and does not—promise", html: "<p>A straight tangent step can eventually leave the curved contour. Zero local rise describes its initial rate, not its height after an arbitrary finite step. At a point where the gradient is zero, every first-order directional rate is zero; there is no unique fastest first-order direction. The same reasoning can describe temperature, profit, or error—not just height.</p>" },
  { slug: "prediction", evidence: "tangent", title: "Try the idea in a changed case", html: "<p>If the eastward slope were negative and the northward slope positive, which quadrant would the gradient point into? What would moving east do? And why can’t a same-length move tilted away from the gradient do better? Think in terms of <strong>local contributions and projection</strong>, not the northeast arrow in this example. Answers are below the card.</p>" }
] as const satisfies readonly { readonly slug: string; readonly evidence: GradientEvidence; readonly title: string; readonly html: string }[]);

export type GradientBeatSlug = typeof gradientContourBeats[number]["slug"];
export function gradientBeatIndex(slug: GradientBeatSlug): number {
  const index = gradientContourBeats.findIndex(beat => beat.slug === slug);
  if (index < 0) throw new Error(`Missing gradient beat: ${slug}`);
  return index;
}
export const gradientComparisonBounds = Object.freeze({ start: gradientBeatIndex("components"), end: gradientBeatIndex("across") });
