import type { CheckedGradientExplanation } from "./gradient-contour-authoring.ts";
import { gradientNumber as f } from "./gradient-contour-story.ts";
import { createKpArticleSource } from "../../article/kp-article-source.ts";
import { compileKpArticleDocument } from "../../article/kp-article-document.ts";
import { resolveKpArticleImports } from "../../article/kp-article-import-lock.ts";
import { compileKpArticleStaticHtml } from "../../article/kp-article-static-html.ts";

export function projectGradientReading(lesson: CheckedGradientExplanation, mode: "full" | "tangent") {
  const { model } = lesson.sequence, { point } = model.source, g = model.atPoint.gradient;
  const context = `We want to predict how a small move changes a quantity. Here the quantity is height: $f(x,y)=${model.latex}$, at $p=(${f(point.x)},${f(point.y)})$. The coordinates use the same horizontal distance units. The starting height is approximately ${f(model.level)}.\n\nA partial derivative is the local rate when one coordinate changes and the other stays fixed. Here the eastward and northward slopes are approximately ${f(g.x)} and ${f(g.y)}. Their pair is the gradient. On the local flat approximation, their contributions add:\n\n$$\\Delta f\\approx f_x\\Delta x+f_y\\Delta y=\\nabla f\\cdot\\Delta\\mathbf r.$$`;
  const full = `## Why equal distance matters\n\nA diagonal move may gain more height simply because it is longer. To compare directions fairly, allow the same small horizontal distance in every direction. For a unit direction $\\mathbf u$, the directional derivative is $D_{\\mathbf u}f=\\nabla f\\cdot\\mathbf u$. This compares initial rates, not distant endpoints.\n\n## Why the gradient wins\n\nThe dot product also equals the gradient's length times the signed projection of your move onto its direction. Split a move into an aligned part and a perpendicular part. The perpendicular part contributes zero first-order rise. All the rise comes from the aligned part.\n\nEqual-length arrows have tips on a circle. No arrow's projection onto a line can exceed its own length. Alignment gives the full length; turning away shortens the projection. Therefore the gradient's direction gives the greatest local rate, approximately ${f(model.atPoint.magnitude)} here. The arrow encodes a direction and a rate, not a commanded travel distance.\n\n## Why contours meet it at right angles\n\nA contour joins points with the same height. A tangent is the contour's immediate direction at a point. Height does not initially change along it, so its dot product with the gradient is zero. At a nonzero gradient this means a right angle. Contours confirm the gradient's meaning; they do not define it.`;
  const tangent = `## Why ask this?\n\nA contour is a path of constant height. Yet a straight step in its tangent direction can leave that height. Understanding the distinction prevents us from treating a local approximation as a promise about a whole path.\n\n## Follow the actual curve\n\nWrite a smooth contour path as $\\mathbf r(s)$, with $\\mathbf r(0)=p$. Move along it with nonzero velocity. Each coordinate changes: multiply its rate by the corresponding coordinate slope, then add. This is the multivariable chain rule. Since height stays constant, it gives\n\n$$0=\\frac{d}{ds}f(\\mathbf r(s))\\big|_{s=0}=\\nabla f(p)\\cdot\\mathbf r'(0).$$\n\nThe vector $\\mathbf r'(0)$ points along the tangent. Its dot product with the nonzero gradient is zero: these directions are perpendicular. A unit tangent can be obtained by rotating the gradient a quarter-turn and normalizing.\n\n## A straight step is a different path\n\nLet $\\mathbf t$ be a unit tangent at the starting point. For this quadratic field, a straight move of signed length $\\varepsilon$ has the exact change\n\n$$f(p+\\varepsilon\\mathbf t)-f(p)=\\varepsilon\\nabla f(p)\\cdot\\mathbf t+\\varepsilon^2(a t_x^2+b t_y^2).$$\n\nHere $a=${f(model.source.a)}$ and $b=${f(model.source.b)}$. The linear term vanishes because the direction is tangent. The quadratic term remains positive for any nonzero step. The contour curves to stay level; the straight line does not. Halving the step quarters this remaining change. That is what flat to first order means.`;
  const limits = "## Limits and a prediction\n\nThese are local first-order statements for smooth fields, with nonzero gradient and comparable coordinate units. At a stationary point all first-order directional rates vanish; there is no unique fastest first-order direction.\n\nBefore revealing the answer, predict: does a small straight tangent step stay exactly at the starting height in this positive quadratic field? What happens to its height change if the step is halved?";
  const id = `lesson.calculus.gradient-${mode}`;
  const source = createKpArticleSource(`${id}.${lesson.revisionId.slice(7)}`, `---\nkp:\n  schema: kp.article.v1\n  id: ${id}\n  imports:\n---\n\n# ${mode === "full" ? "What is a gradient, and why does it point uphill?" : "Why is the contour tangent flat to first order?"}\n\n${context}\n\n${mode === "full" ? full : tangent}\n\n${limits}\n`);
  const lock = resolveKpArticleImports(source, []).lock;
  const { document } = compileKpArticleDocument({ source, registry: [], lock });
  const html = compileKpArticleStaticHtml(document, { headingIdPrefix: id }).articleHtml;
  return Object.freeze({ mode, revisionId: lesson.revisionId, source, document, html,
    answer: "No. The initial rate is zero, but the remaining quadratic term raises the height. Halving the straight step quarters that height change. Following the curved contour instead keeps height exactly constant." });
}
